### ISSUE TITLE
Support for css.include for Native

### ISSUE THREAD

**Issue by efoken** [facebook/react-strict-dom#111]
### Describe the feature request

I don't know if `stylex.include` is an official StyleX API? But with react-strict-dom the `css.include` works on Web, but not for Native.

Example:

```tsx
import { typography } './globals.stylex';

export const styles = css.create({
  root: {
    color: '#000',
  },
  large: {
    ...css.include(typography.bodyLarge),
  },
});
```

For Native I tried to use normal object spread, and it worked:

```tsx
import { typography } './globals.stylex';

export const styles = css.create({
  // ...
  large: {
    ...typography.bodyLarge,
  },
});
```

**Comment by necolas** [comment]
`stylex.include` is not a StyleX API we expect to keep. We don't use it internally

**Comment by efoken** [comment]
Good to know, thanks 🙏 But how is it possible to use object spreading?

**Comment by nmn** [comment]
> But how is it possible to use object spreading?

This happens due to some implementation details, but is not a supported pattern either.

**Comment by efoken** [comment]
Yeah I know @nmn 😉 I meant, what is the recommended way to handle this case when I want to include typography style into another style? What can I use instead of `css.include`?

**Comment by necolas** [comment]
You just add the style into the array of styles passed as a prop - it's the default way that styles are composed in RN and StyleX
