### ISSUE TITLE
Rename label `for` prop to `htmlFor`

### ISSUE THREAD

**Issue by efoken** [facebook/react-strict-dom#119]
### Describe the feature request

According to React documentation:

> Since `for` is a reserved word in JavaScript, React elements use `htmlFor` instead.

Which is actually true. Even if you can use `for` as a prop in JSX and also as an object key, there are several use-cases where it does not work, for example when using object destructuring:

```tsx
const { for, ...rest } = props;
```

**Comment by necolas** [comment]
You can simply rename the prop when destructuring. We've already codemod this prop internally and it's been fine so far, so will leave it as-is for now
