### ISSUE TITLE
React strict dom doesn't work on expo web

### ISSUE THREAD

**Issue by hyochan** [facebook/react-strict-dom#199]
### Describe the issue

I am facing below error when running example app in `expo web`. It work fine on `iOS`.

<img width="600" alt="Screenshot 2024-09-04 at 1 06 21 PM" src="https://github.com/user-attachments/assets/aa1c22eb-a81b-4336-a928-880baa4ffe4d">

```
localhost/:35 
        
        
       GET http://localhost:8081/src/index.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app net::ERR_ABORTED 500 (Internal Server Error)Understand this error
localhost/:1 Refused to execute script from 'http://localhost:8081/src/index.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.Understand this error
```

### Expected behavior

Works fine on web

### Steps to reproduce

`cd apps/examples`

`yarn && yarn dev:web`

**Comment by necolas** [comment]
> `yarn && yarn dev:web`

Please see the contributing file to see how to install and run things. This repo uses npm workspaces, not yarn
