### ISSUE TITLE
npm run dev:web not working for example

### ISSUE THREAD

**Issue by dsm23** [facebook/react-strict-dom#200]
### Describe the issue

By copying the example from your repo and pasting in its own repository. The command

```
npm run dev:web
```
results in the following error message

```
Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 493ms src/index.js (1 module)
Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "src/index.js"
```

By adding a `workspaces` key to the `package.json` makes it work as expected even if that workspaces refers to a folder that doesn't exist

### Expected behavior

I would expect the example to work out of the box.

### Steps to reproduce

Google Chrome:
Version 128.0.6613.120 (Official Build) (x86_64)

macOs Sonoma 14.6.1 (23G93)

### Test case

https://github.com/dsm23/example-for-react-strict-dom-issue

**Comment by necolas** [comment]
See https://github.com/facebook/react-strict-dom/blob/main/CONTRIBUTING.md#development

> In another process, start the examples app:
> `npm run dev -w examples`
