### ISSUE TITLE
bug(React Native, TypeScript): Non-string `transform` property is disallowed as a type

### ISSUE THREAD

**Issue by tjzel** [facebook/react-strict-dom#204]
### Describe the issue

React-Native-like `transform` property is disallowed by TypeScript but works as expected in runtime.

![Screenshot 2024-09-20 at 13 15 27](https://github.com/user-attachments/assets/912060be-70d4-46ea-a6ad-f7b2d615e7a9)

<details>
<summary> Repro </summary>

```tsx
import React from 'react';
import { css, html } from 'react-strict-dom';

const styles = css.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kickedBox: {
    width: '100px',
    height: '100px',
    backgroundColor: 'blue',
    transform: [{ rotate: '45deg' }],
  },
});

export default function App() {
  return (
    <html.div style={styles.container}>
      <html.div style={styles.kickedBox} /> 
      {/* Error: `transform` property is expected to be a string */}
    </html.div>
  );
}
```

</details>

<details>
<summary>
Screenshot from app
</summary>

![simulator_screenshot_F9F6B96B-7B19-440C-A009-1E27814FF7EF](https://github.com/user-attachments/assets/a2bab9b3-8be6-43ab-adef-5bf26944cdf8)

</details>

### Expected behavior

There's no TypeScript error or there's a runtime error about incompatible types.

### Steps to reproduce

See the code with the reproduction.

### Additional comments

react-native@0.75.2
react-strict-dom@0.0.27

**Comment by nmn** [comment]
Should we close this issue?

**Comment by tjzel** [comment]
Why should we close it? The code that yield the type error works perfectly fine in React Native.

**Comment by nmn** [comment]
@tjzel The goal of `react-strict-dom` is to provide a unified API for styles that work on both React Native *and* the web. The type error in your example is correctly warning you against code that wouldn't work on the web. There are similar type errors for styles that work on the web and not React Native.

Instead of using `{rotate: '45deg'}` use `'rotate(45deg)'`.

**Comment by tjzel** [comment]
While I understand the drive for a unified API, I don't think forwarding the API that's based on string interpolation is the correct measure here. I'd much rather embrace JavaScript instead of CSS here - but that's maybe due to fact I do more native than web. Regardless, thanks for your insight on this.
