### ISSUE TITLE
css.props breaks pseudo class support

### ISSUE THREAD

**Issue by dgca** [facebook/react-strict-dom#234]
### Describe the issue

On React Native, using the `css.props(...styles)` syntax to merge props causes pseudo classes such as `:active` to stop working.

### Expected behavior

In the example below, the button turns blue on pointer down when `style={styles.base}` is used, but not `{...css.props(styles.base)}`

```ts
const styles = css.create({
  base: {
    backgroundColor: {
      default: "red",
      ":active": "blue",
    },
  },
});

export function Button({ title }: Props) {
  return (
    <html.button
      style={styles.base} // this works
      // {...css.props(styles.base)} but this does not
    >
      Pess me
    </html.button>
  );
}
```

### Steps to reproduce

Using:

- `react-strict-dom@0.0.28`
- `react-native@0.75`
- New arch enabled and pointer down feature flags enabled

**Comment by necolas** [comment]
`css.props` is not meant to be used on `html.*` elements. it's not documented, and best to think of it as an internal API that we'll eventually avoid including on the `css` object altogether

Please refer to the API docs for more information https://facebook.github.io/react-strict-dom/api/

**Comment by dgca** [comment]
@necolas Is there a recommended way to do conditional styles based on props?

**Comment by necolas** [comment]
It's in the docs https://facebook.github.io/react-strict-dom/api/html/common/

<img width="984" alt="image" src="https://github.com/user-attachments/assets/ee1bef5c-08a8-42dd-9e1f-637ad0fd9fd9">

**Comment by dgca** [comment]
Amazing, ty
