### ISSUE TITLE
`react-strict-dom/babel` export missing

### ISSUE THREAD

**Issue by HorusGoul** [facebook/react-strict-dom#240]
### Describe the issue

A breaking change was introduced in https://github.com/facebook/react-strict-dom/commit/3431c9f9c71b615fa3b227b3f7df916703dd6198 (0.0.29), which is affecting the `vite-plugin-stylex` package, see this issue: https://github.com/HorusGoul/vite-plugin-stylex/issues/93

We use the `react-strict-dom/babel` export when folks configure the import source like this:

```ts
    styleX({
      importSources: [
        {
          from: "react-strict-dom",
          as: "css",
        },
      ],
    }),
```

We do it here:

https://github.com/HorusGoul/vite-plugin-stylex/blob/85833306d294526e767def8a6f596c8fa4d87b6f/packages/vite-plugin-stylex/src/main.mts#L338

### Expected behavior

Importing `react-strict-dom/babel` should return the babel plugin for RSD.

### Steps to reproduce

1. Install the latest `react-strict-dom` version
2. `require('react-strict-dom/babel')`
3. Won't work

### Additional comments

I understand the preset facilitates usage, but some folks might want additional configuration options for the underlying StyleX plugin included in the preset.

So, what's the plan? I can contribute the `/babel` export back if needed!

Thanks!

**Comment by necolas** [comment]
You should probably remove the RSD dependency from your project. RSD is prescriptive about how StyleX is used

**Comment by carloslibardo** [comment]
@necolas possible some bug at react-strict-dom? i'm having trouble using vite with RSD.

**Comment by necolas** [comment]
Please read the docs https://facebook.github.io/react-strict-dom/api/babel-preset/

**Comment by carloslibardo** [comment]
I already read, for me it's right.

I cannot use RSD at 0.0.34 because i'm getting this issue error.

``` js
// vite.config.ts
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import styleX from "vite-plugin-stylex";

export default defineConfig({
  plugins: [react(), styleX({
    importSources: [
      {
        from: "react-strict-dom",
        as: "css",
      },
      ],
    }),
  ],
});
```

If i remove styleX config i got this error:

```js
stylex.create should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin' 
```

```js
// postcss.config.js
module.exports = {
  plugins: {
    "postcss-react-strict-dom": {
      include: ["src/**/*.{js,jsx,mjs,ts,tsx}"],
    },
    autoprefixer: {},
  },
};

```

```js
// babel.config.js
import reactStrictBabelPreset from "react-strict-dom/babel-preset";

export default function babelConfig() {
  return {
    presets: [[reactStrictBabelPreset, { debug: true }]],
  };
}



```

**Comment by necolas** [comment]
Use the latest version of RSD. Don't use `vite-plugin-stylex` at all. The RSD preset and PostCSS does it all, you only need to follow the setup instructions.

**Comment by zaydek** [comment]
@carloslibardo If you get something working do you mind providing a minimal repro?

**Comment by carloslibardo** [comment]
@zaydek sure! i'm trying, but still don't understand what i'm missing, already followed the setup guide and shared my config files.

When i running the application using vite, the following error is:

```Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'```

**Comment by necolas** [comment]
You should try setting up Vite as a React project using Babel plugins. Your config files don't seem to even connect Vite to your Babel config - https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react

**Comment by carloslibardo** [comment]
@necolas i'm using ``configFile`` prop, to ensure my babel.config.js is being read, thats something i was missing, but keep getting the error.

**Comment by zaydek** [comment]
Also having issues: created https://github.com/zaydek/experimental-react-strict-dom and also here's a quick video explaining the problem (video is slightly longer than one minute)

https://github.com/user-attachments/assets/2d640023-51ae-4365-be0f-25cf612a8592

**Comment by carloslibardo** [comment]
@zaydek about the cache problem i solve setting cache to true in babel.config.js

```js
import reactStrictBabelPreset from "react-strict-dom/babel-preset";

export default function babelConfig(api) {
  api.cache(true);
  return {
    presets: [[reactStrictBabelPreset, { rootDir: process.cwd() }]],
  };
}

```

**Comment by necolas** [comment]
I don't use Vite but I don't see where you're telling Vite about the babel config - https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#babel

**Comment by carloslibardo** [comment]
```js
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    react({
      babel: {
        configFile: true
      }
    })
  ],
});

```

setting the configFile as true should be enough to telling Vite about the babel config

**Comment by necolas** [comment]
If you get this warning, it means the babel plugin isn't being used:

```
stylex.create should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'
```

**Comment by zaydek** [comment]
I think we should loop @javascripter in or create a dedicated issue. Obviously this is an integration issue. 

https://github.com/zaydek/experimental-react-strict-dom is now updated to use the API caching thing you mentioned @carloslibardo as well as the React Babel config file thing.

Same problem persists

```
chunk-V77ST7QI.js?v=ab91b9a2:140 Uncaught Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'
    at errorForFn (chunk-V77ST7QI.js?v=ab91b9a2:140:28)
    at stylexCreate (chunk-V77ST7QI.js?v=ab91b9a2:171:9)
    at react-strict-dom_runtime.js?v=ab91b9a2:8:14
errorForFn @ chunk-V77ST7QI.js?v=ab91b9a2:140
stylexCreate @ chunk-V77ST7QI.js?v=ab91b9a2:171
(anonymous) @ react-strict-dom_runtime.js?v=ab91b9a2:8Understand this errorAI
```

So necolas is right in pointing out that Babel is not properly being invoked and this likely has nothing to do with RSD.

**Comment by necolas** [comment]
It's probably an issue with the postcss package:

```
chunk-V77ST7QI.js?v=ab91b9a2:140 Uncaught Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'
    at errorForFn (chunk-V77ST7QI.js?v=ab91b9a2:140:28)
    at stylexCreate (chunk-V77ST7QI.js?v=ab91b9a2:171:9)
    at react-strict-dom_runtime.js?v=ab91b9a2:8:14
```

This error is pointing to `react-strict-dom_runtime.js`, which is a file in the RSD package.

The following code in the RSD postcss plugin is only including the resolved entry file for the package.

https://github.com/javascripter/postcss-react-strict-dom/blob/main/src/index.ts#L17-L22

But it looks like it also needs to include the runtime entry file

https://github.com/facebook/react-strict-dom/blob/main/packages/react-strict-dom/package.json#L11

**Comment by carloslibardo** [comment]
@necolas i tried it but still not working :c

this my vite.config file

``` js
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    react({
      babel: {
        configFile: true,
        include: [/react-strict-dom/, /@stylexjs/, /\.[jt]sx?$/],
      },
    }),
  ],
  optimizeDeps: {
    include: ["react-strict-dom"],
    force: true,
  },
});
```

i'm going stop now, but tomorrow can keep debugging and trying to find a solution, any help is welcome =)

**Comment by carloslibardo** [comment]
Still cannot make it works, @necolas should i open a new issue addresing that?

**Comment by javascripter** [comment]
> Uncaught Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'

postcss-react-strict-dom doesn't actually run the code at runtime (it just extracts css without running user code), so this runtime error is caused by vite not transforming source code/node_modules with babel.

I'm not very familiar with vite but i think it's probably not related to postcss config.

**Comment by carloslibardo** [comment]
I created a issue for that: https://github.com/facebook/react-strict-dom/issues/265

**Comment by efoken** [comment]
@carloslibardo `optimizeDeps.include` handles react-strict-dom with esbuild, not babel. There is a Vite plugin to change that: https://www.npmjs.com/package/vite-plugin-babel

**Comment by efoken** [comment]
Also note that `vite-plugin-stylex` is not working anymore. It does not run with Vite 6 and also does not include `react-strict-dom/babel-preset`. There is `stylex-extend` which runs great with StyleX, but does not work with RSD: https://github.com/nonzzz/stylex-extend

To get RSD running with Vite, see my comment in https://github.com/facebook/react-strict-dom/issues/265
