### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by necolas** [facebook/react-strict-dom#25]
### Describe the feature request

Generate a TypeScript libdef for the npm package

**Comment by nmn** [comment]
I'm overhauling the build setup which will include this.

**Comment by margalit** [comment]
Thanks! In the meantime it is at least possible to get the types for css from styleX:
```
// types.d.ts
declare module "react-strict-dom" {
  // CSS is a re-export of the module "@stylexjs/stylex";
  export * as css from "@stylexjs/stylex";
}
```

**Comment by TomMarius** [comment]
I can help out with TypeScript. Do you have any ideas on how to approach it? Do you want to support Flow as well as TS? I'm not sure if we could generate high-quality TS types from Flow, but we could explore that.

**Comment by necolas** [comment]
This should be fixed in 0.0.3 which was released after #36 was merged

**Comment by nandorojo** [comment]
I'm on `0.0.34` and TypeScript support does not appear to work. Might need to re-open this issue.

<img width="489" alt="Image" src="https://github.com/user-attachments/assets/233491aa-b4b8-4699-b5d2-a8bb1c9f3812" />

I don't see a `types` field in the `package.json`, I predict this is the problem. It should point to `dist/native/index.d.ts` or `dist/web/index.d.ts`. I can PR this.

**Comment by nandorojo** [comment]
PR here: https://github.com/facebook/react-strict-dom/pull/268

I see this after applying the change locally:

<img width="546" alt="Image" src="https://github.com/user-attachments/assets/256ec9d7-a201-4848-95f9-b65164f5f646" />
