### ISSUE TITLE
Cannot run example project on Android emulator

### ISSUE THREAD

**Issue by dlpmmk** [facebook/react-strict-dom#43]
### Describe the issue

I cloned the project normally, then installed the dependencies, and configured the Android development tools accordingly.
Then run `yarn dev:android`. At this time, a simulated mobile phone will be automatically started, and then the following error will be reported.

### Expected behavior

```sh
Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling failed 6179ms (src/index.js)
Unable to resolve "react-strict-dom" from "src/App.js"
```

### Steps to reproduce

1. run `yarn dev:android`

**Comment by dlpmmk** [comment]
now, I run command `yarn add  eact-strict-dom` in the examples folder and it can run. sorry

**Comment by dlpmmk** [comment]
add the `react-strict-dom` package in examples path

**Comment by necolas** [comment]
FWIW, per the contributing guidelines, the repo uses npm not yarn https://github.com/facebook/react-strict-dom/blob/main/CONTRIBUTING.md
