### ISSUE TITLE
Custom npm package using RSD

### ISSUE THREAD

**Issue by iketw** [facebook/react-strict-dom#49]
### Describe the issue

I'm building an npm package that exports a button built with RSD. I should be able to use this package in both a RN app and a React app.

https://github.com/iketw/rsd

### Expected behavior

I can do:

`import { ButtonRSD} from 'ike-rsd'` in React Native and I successfully can use the button functionality.

In my vite app I keep getting:

```
chunk-FW4L2DMG.js?v=7e19444c:202 Uncaught Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin'
```

With the following babel config:

https://github.com/iketw/rsd/blob/main/babel.config.js

### Steps to reproduce

1. yarn add ike-rsd
2. `import { ButtonRSD} from 'ike-rsd'`
3. Use `<ButtonRSD />` in a vite app

**Comment by necolas** [comment]
Please refer to StyleX for information on how to setup the library with Vite https://github.com/facebook/stylex

You can't use `api.caller(getPlatform)` in your babel config unless your bundler setup is providing that information, as it is in the Expo + Metro setup. For Vite (web only) follow the StyleX instructions

**Comment by DannyRoberts22** [comment]
Hey @iketw Don't suppose you figured this out? The StyleX docs are pretty terrible.

**Comment by necolas** [comment]
Start here https://facebook.github.io/react-strict-dom/learn/setup/

**Comment by nmn** [comment]
@iketw When using StyleX (and RSD) in a package, you need to do two things:
1. Ensure that the package is published uncompiled
2. Ensure that your Vite app that uses the package compiles the dependency

The Babel config you shared only applies to the app code by default and anything in the node_modules folder is excluded from transpilation. You can configure the Babel plugin in Vite to explicitly `include` your package.

----

@DannyRoberts22 What is not answered well in the StyleX docs?
