### ISSUE TITLE
Fix support for Media Query syntax in StyleX shim

### ISSUE THREAD

**Issue by necolas** [facebook/react-strict-dom#51]
### Describe the issue

The correct syntax for Media Queries in StyleX is not supported in the native shim. We only support a legacy syntax.

### Expected behavior

See https://stylexjs.com/docs/learn/styling-ui/defining-styles/#media-queries-and-other--rules

### Steps to reproduce

N/A

**Comment by vincentriemer** [comment]
Should be straightforward — I can take this on
