### ISSUE TITLE
ESLint Plugin mixes both ESM and CommonJS artifacts in dist/ dir

### ISSUE THREAD

**Issue by javascripter** [facebook/react-strict-dom#63]
### Describe the issue

Published npm package `eslint-plugin-react-strict-dom` includes both ESM and CommonJS in dist/ directory, causing problems when loading the ESLint Plugin.

This file is in ESM, but imports ./valid-styles which is  CommonJS.
`dist/index.js`
```javascript
'use strict';

import validStyles from './valid-styles';
const rules = {
  'valid-styles': validStyles
};
export { rules };
```

`dist/valid-styles.js`
```javascript dist/valid-styles.js
// ...
module.exports = rule;
```

### Expected behavior

`dist/` should be compiled either in CommonJS or ESM, but not mix both formats at the same time.

### Steps to reproduce

By inspecting files in node_modules/eslint-plugin-react-strict-dom/dist or see published code at [npm page](https://www.npmjs.com/package/eslint-plugin-react-strict-dom?activeTab=code)

`node_modules/eslint-plugin-react-strict-dom/dist/index.js`
<img width="695" alt="Screenshot 2024-03-27 at 19 59 29" src="https://github.com/facebook/react-strict-dom/assets/13040/d15f27ab-81a3-4109-9714-aa3fe0ea2684">

`node_modules/eslint-plugin-react-strict-dom/dist/valid-styles.js`: 
<img width="705" alt="Screenshot 2024-03-27 at 19 59 47" src="https://github.com/facebook/react-strict-dom/assets/13040/6a4eae17-13a9-4837-b008-2ac0cda43671">

**Comment by necolas** [comment]
PR https://github.com/facebook/react-strict-dom/pull/74
