### ISSUE TITLE
Improve onClick event payload shim to include methods

### ISSUE THREAD

**Issue by necolas** [facebook/react-strict-dom#77]
### Describe the issue

The onClick event shim doesn't include methods like `stopPropagation`, which we use on web. The shim can either delegate to the underlying React Native methods or make them noops (with warnings) so code doesn't throw when calling them.

### Expected behavior

App doesn't crash / throw at runtime when `click` event methods are called

### Steps to reproduce

1. Call `stopPropagation()` on `click` event on native

**Comment by nmn** [comment]
What are the underlying React Native methods to stop propagation?
